/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.basic.calculatorapplication;
import java.lang.Math.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Manik
 */
public class CalculatorJFrame extends javax.swing.JFrame {
    
    float Number1,Answer,Number2;
    int Calculation;
    
   
    
    public void arithmetic_operations()
    {
        switch(Calculation)
        {
            case 1:
                Answer = Number1 + Float.parseFloat(ResultField.getText());
                ResultField.setText(Double.toString(Answer));
                break;
            case 2:
                Answer = Number1 - Float.parseFloat(ResultField.getText());
                ResultField.setText(Double.toString(Answer));
                break;
            case 3:
                Answer = Number1 * Float.parseFloat(ResultField.getText());
                ResultField.setText(Double.toString(Answer));
                break;
            case 4:
                Answer = Number1 / Float.parseFloat(ResultField.getText());
                ResultField.setText(Double.toString(Answer));
                break;
        }
    }
   
    

    /**
     * Creates new form CalculatorJFrame
     */
    public CalculatorJFrame() {
        initComponents();
        AdditionButton.setEnabled(false);
        BackspaceButton.setEnabled(false);
        SubstractButton.setEnabled(false);
        DivideButton.setEnabled(false);
        MultiplyButton.setEnabled(false);
        PercentageButton.setEnabled(false);
        EqualsButton.setEnabled(false);
        DecimalButton.setEnabled(false);
        CEButton.setEnabled(false);
        DoubleZeroButton.setEnabled(false);
        ZeroButton.setEnabled(false);
        OneButton.setEnabled(false);
        TwoButton.setEnabled(false);
        ThreeButton.setEnabled(false);
        FourButton.setEnabled(false);
        FiveButton.setEnabled(false);
        SixButton.setEnabled(false);
        SevenButton.setEnabled(false);
        EightButton.setEnabled(false);
        NineButton.setEnabled(false);
        ResultField.setEnabled(false);
        SquareRootButton.setEnabled(false);
        OffButton.setSelected(true);
        Icon icon = new ImageIcon("E:\\My WorkSpace\\Java Coding 2020\\CalculatorApplication\\src\\main\\java\\com\\basic\\calculatorapplication\\Backspace.png");
        BackspaceButton.setIcon(icon);
        
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnOffButtonGroup = new javax.swing.ButtonGroup();
        ResultField = new javax.swing.JTextField();
        OnButton = new javax.swing.JRadioButton();
        OffButton = new javax.swing.JRadioButton();
        BackspaceButton = new javax.swing.JButton();
        CEButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        DoubleZeroButton = new javax.swing.JButton();
        DecimalButton = new javax.swing.JButton();
        SquareRootButton = new javax.swing.JButton();
        PercentageButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        SubstractButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setLocation(new java.awt.Point(300, 150));
        setName("CalculatorFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(300, 330));
        setType(java.awt.Window.Type.UTILITY);

        ResultField.setEditable(false);
        ResultField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        ResultField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        OnOffButtonGroup.add(OnButton);
        OnButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        OnButton.setText("ON");
        OnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnButtonActionPerformed(evt);
            }
        });

        OnOffButtonGroup.add(OffButton);
        OffButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        OffButton.setText("OFF");
        OffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffButtonActionPerformed(evt);
            }
        });

        BackspaceButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        BackspaceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BackspaceButton.setFocusCycleRoot(true);
        BackspaceButton.setFocusable(false);
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        CEButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        CEButton.setText("CE");
        CEButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CEButton.setFocusCycleRoot(true);
        CEButton.setFocusable(false);
        CEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEButtonActionPerformed(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        SevenButton.setText("7");
        SevenButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SevenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SevenButton.setFocusCycleRoot(true);
        SevenButton.setFocusable(false);
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        EightButton.setText("8");
        EightButton.setFocusCycleRoot(true);
        EightButton.setFocusable(false);
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        NineButton.setText("9");
        NineButton.setFocusCycleRoot(true);
        NineButton.setFocusable(false);
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        FourButton.setText("4");
        FourButton.setFocusCycleRoot(true);
        FourButton.setFocusable(false);
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        FiveButton.setText("5");
        FiveButton.setFocusCycleRoot(true);
        FiveButton.setFocusable(false);
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        SixButton.setText("6");
        SixButton.setFocusCycleRoot(true);
        SixButton.setFocusable(false);
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        TwoButton.setText("2");
        TwoButton.setFocusCycleRoot(true);
        TwoButton.setFocusable(false);
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        OneButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        OneButton.setText("1");
        OneButton.setFocusCycleRoot(true);
        OneButton.setFocusable(false);
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.setFocusCycleRoot(true);
        ThreeButton.setFocusable(false);
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.setFocusCycleRoot(true);
        ZeroButton.setFocusable(false);
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        DoubleZeroButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        DoubleZeroButton.setText("00");
        DoubleZeroButton.setFocusCycleRoot(true);
        DoubleZeroButton.setFocusable(false);
        DoubleZeroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DoubleZeroButton.setMargin(new java.awt.Insets(2, -2, 2, -2));
        DoubleZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleZeroButtonActionPerformed(evt);
            }
        });

        DecimalButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        DecimalButton.setText(".");
        DecimalButton.setFocusCycleRoot(true);
        DecimalButton.setFocusable(false);
        DecimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecimalButtonActionPerformed(evt);
            }
        });

        SquareRootButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        SquareRootButton.setText("√");
        SquareRootButton.setFocusCycleRoot(true);
        SquareRootButton.setFocusable(false);
        SquareRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareRootButtonActionPerformed(evt);
            }
        });

        PercentageButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        PercentageButton.setText("%");
        PercentageButton.setFocusCycleRoot(true);
        PercentageButton.setFocusable(false);
        PercentageButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        PercentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageButtonActionPerformed(evt);
            }
        });

        DivideButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        DivideButton.setText("÷");
        DivideButton.setFocusCycleRoot(true);
        DivideButton.setFocusable(false);
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        MultiplyButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        MultiplyButton.setText("X");
        MultiplyButton.setFocusCycleRoot(true);
        MultiplyButton.setFocusable(false);
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });

        SubstractButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        SubstractButton.setText("-");
        SubstractButton.setFocusCycleRoot(true);
        SubstractButton.setFocusable(false);
        SubstractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubstractButtonActionPerformed(evt);
            }
        });

        EqualsButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        EqualsButton.setText("=");
        EqualsButton.setFocusCycleRoot(true);
        EqualsButton.setFocusable(false);
        EqualsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsButtonActionPerformed(evt);
            }
        });

        AdditionButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.setFocusCycleRoot(true);
        AdditionButton.setFocusable(false);
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DoubleZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DecimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SubstractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(ResultField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OffButton)
                            .addComponent(OnButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OffButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubstractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoubleZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffButtonActionPerformed
        AdditionButton.setEnabled(false);
        BackspaceButton.setEnabled(false);
        SubstractButton.setEnabled(false);
        DivideButton.setEnabled(false);
        MultiplyButton.setEnabled(false);
        PercentageButton.setEnabled(false);
        EqualsButton.setEnabled(false);
        DecimalButton.setEnabled(false);
        CEButton.setEnabled(false);
        DoubleZeroButton.setEnabled(false);
        ZeroButton.setEnabled(false);
        OneButton.setEnabled(false);
        TwoButton.setEnabled(false);
        ThreeButton.setEnabled(false);
        FourButton.setEnabled(false);
        FiveButton.setEnabled(false);
        SixButton.setEnabled(false);
        SevenButton.setEnabled(false);
        EightButton.setEnabled(false);
        NineButton.setEnabled(false);
        ResultField.setEnabled(false);
        SquareRootButton.setEnabled(false);
        ResultField.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_OffButtonActionPerformed

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonActionPerformed
        String ResultFieldText = ResultField.getText();
        if(ResultFieldText.equals("1")||ResultFieldText.equals("2")||ResultFieldText.equals("3")||ResultFieldText.equals("4")||ResultFieldText.equals("5")||ResultFieldText.equals("6")||ResultFieldText.equals("7")||ResultFieldText.equals("8")||ResultFieldText.equals("9"))
            {
                    ResultField.setText("");
                    ResultField.setText("0");
            }
        else
        {
            ResultField.setText(ResultFieldText.replace(ResultFieldText.substring(ResultFieldText.length()-1),""));// TODO add your handling code here:
        }
    }//GEN-LAST:event_BackspaceButtonActionPerformed

    private void SquareRootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareRootButtonActionPerformed
        String ResultFieldText = ResultField.getText();
        Answer = (float)Math.sqrt(Double.parseDouble(ResultFieldText));
        ResultField.setText(Double.toString(Answer));
        // TODO add your handling code here:
    }//GEN-LAST:event_SquareRootButtonActionPerformed

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("0");
        }
        else
        {
            ResultField.setText(PreviousValue+"0");
        }
        
    }//GEN-LAST:event_ZeroButtonActionPerformed

    private void DoubleZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleZeroButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("0");
        }
        else
        {
            ResultField.setText(PreviousValue+"00");
        }// TODO add your handling code here:
    }//GEN-LAST:event_DoubleZeroButtonActionPerformed

    private void OnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnButtonActionPerformed
        AdditionButton.setEnabled(true);
        BackspaceButton.setEnabled(true);
        SubstractButton.setEnabled(true);
        DivideButton.setEnabled(true);
        MultiplyButton.setEnabled(true);
        PercentageButton.setEnabled(true);
        EqualsButton.setEnabled(true);
        DecimalButton.setEnabled(true);
        CEButton.setEnabled(true);
        DoubleZeroButton.setEnabled(true);
        ZeroButton.setEnabled(true);
        OneButton.setEnabled(true);
        TwoButton.setEnabled(true);
        ThreeButton.setEnabled(true);
        FourButton.setEnabled(true);
        FiveButton.setEnabled(true);
        SixButton.setEnabled(true);
        SevenButton.setEnabled(true);
        EightButton.setEnabled(true);
        NineButton.setEnabled(true);
        ResultField.setEnabled(true);
        SquareRootButton.setEnabled(true);
        ResultField.setText("0");       // TODO add your handling code here:
    }//GEN-LAST:event_OnButtonActionPerformed

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("1");
        }
        else
        {
            ResultField.setText(PreviousValue+"1");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_OneButtonActionPerformed

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))        {
            ResultField.setText("");
            ResultField.setText("2");
        }
        else
        {
            ResultField.setText(PreviousValue+"2");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_TwoButtonActionPerformed

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("3");
        }
        else
        {
            ResultField.setText(PreviousValue+"3");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ThreeButtonActionPerformed

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("4");
        }
        else
        {
            ResultField.setText(PreviousValue+"4");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_FourButtonActionPerformed

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("5");
        }
        else
        {
            ResultField.setText(PreviousValue+"5");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_FiveButtonActionPerformed

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("6");
        }
        else
        {
            ResultField.setText(PreviousValue+"6");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_SixButtonActionPerformed

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("7");
        }
        else
        {
            ResultField.setText(PreviousValue+"7");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_SevenButtonActionPerformed

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("8");
        }
        else
        {
            ResultField.setText(PreviousValue+"8");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_EightButtonActionPerformed

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineButtonActionPerformed
        String PreviousValue = ResultField.getText();
        if (PreviousValue.equals("0"))
        {
            ResultField.setText("");
            ResultField.setText("9");
        }
        else
        {
            ResultField.setText(PreviousValue+"9");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_NineButtonActionPerformed

    private void DecimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecimalButtonActionPerformed
        String ResultFieldText = ResultField.getText();
        if(ResultFieldText.contains("."))
        {
            ResultField.setText(ResultFieldText+"");
        }
        else
        {
            ResultField.setText(ResultFieldText+".");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_DecimalButtonActionPerformed

    private void CEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEButtonActionPerformed
        ResultField.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_CEButtonActionPerformed

    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
        Number1 = Float.parseFloat(ResultField.getText());
        Calculation = 1;
        ResultField.setText("0");
        
        
        
            // TODO add your handling code here:
    }//GEN-LAST:event_AdditionButtonActionPerformed

    private void EqualsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsButtonActionPerformed
        arithmetic_operations();        // TODO add your handling code here:
    }//GEN-LAST:event_EqualsButtonActionPerformed

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideButtonActionPerformed
        Number1 = Float.parseFloat(ResultField.getText());
        Calculation = 4;
        ResultField.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_DivideButtonActionPerformed

    private void SubstractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubstractButtonActionPerformed
        Number1 = Float.parseFloat(ResultField.getText());
        Calculation = 2;
        ResultField.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_SubstractButtonActionPerformed

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyButtonActionPerformed
        Number1 = Float.parseFloat(ResultField.getText());
        Calculation = 3;
        ResultField.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplyButtonActionPerformed

    private void PercentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageButtonActionPerformed
        
        
    }//GEN-LAST:event_PercentageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton BackspaceButton;
    private javax.swing.JButton CEButton;
    private javax.swing.JButton DecimalButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton DoubleZeroButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JRadioButton OffButton;
    private javax.swing.JRadioButton OnButton;
    private javax.swing.ButtonGroup OnOffButtonGroup;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton PercentageButton;
    private javax.swing.JTextField ResultField;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton SquareRootButton;
    private javax.swing.JButton SubstractButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    // End of variables declaration//GEN-END:variables
}
